### ISSUE TITLE
Google Cloud Build :- Error: Detected unknown package 'espressif8266'

### ISSUE THREAD

**Issue by ben700** [alvarowolfx/gcloud-ota-arduino-update#9]
Build ends with

PlatformManager: Installing espressif8266
Error: Detected unknown package 'espressif8266'
ERROR
ERROR: build step 0 "sglahn/platformio-core:3.6.0" failed: step exited with non-zero status: 1

log.txt

No changes to source, was working till 24th March Google Cloud Support are totally rubbish. I get the same error on all repositories including this one
[log.txt](https://github.com/alvarowolfx/gcloud-ota-arduino-update/files/6339601/log.txt)

**Comment by ben700** [comment]
I raised Case#27454405 with GCP Support, they don't know nothing about anything but they did say 

Additionally, I just want to clarify that the user “alvarowolfx” does not work for Google. However, he does seems to be a great contributor to the GCP community.

**Comment by alvarowolfx** [comment]
I'm gonna try to run some tests here, but have you tried using the latest version of the Docker image instead of v3.6.0 ? Seems like platformio core now is on version 5.1.0

**Comment by alvarowolfx** [comment]
There is a lot of issues related to the custom docker image https://github.com/sglahn/docker-platformio-core . I tried to use the latest version here and got some permissions issues.

In the end, I just used a Python container on Google Cloud Build, installed PlatformIO CLI, ran build and things worked like a charm.

![Screen Shot 2021-04-19 at 10 54 38 PM](https://user-images.githubusercontent.com/1615543/115330718-9e526900-a162-11eb-804b-0ab30ad20725.png)
![Screen Shot 2021-04-19 at 10 56 03 PM](https://user-images.githubusercontent.com/1615543/115330722-a0b4c300-a162-11eb-998c-f3bb822463b5.png)

I updated the cloudbuild.yaml with the fixes, so I hope that helps you with your project.

**Comment by ben700** [comment]
I will try, I will give you access to my GCP if it helps.


I would also like to pay you for some work! Just let me know if your
interested or not.

Ben

**Comment by ben700** [comment]
I got the

PermissionError: [Errno 13] Permission denied: '/builder/home/.platformio'

when i went to 5.1.0 from 3.6.0

**Comment by ben700** [comment]
I tried going with python and I got a different error 

Indexing .pio/build/esp8266/libfd9/libArduinoJson.a
========================= [FAILED] Took 32.93 seconds =========================
ERROR
ERROR: build step 0 "python" failed: step exited with non-zero status: 1

[pythonLog.txt](https://github.com/alvarowolfx/gcloud-ota-arduino-update/files/6340500/pythonLog.txt)

I will look into it but it passed the esP8266 line it was failing on

**Comment by ben700** [comment]
I have got one of my projects to build following change to python.

The one that built has the .pio dir checked into github while the others that fail have .pio in .gitignore

**Comment by ben700** [comment]
as long as .pio is uploaded manually seams to work. Thanks for your help

Fix was to change Python container on Google Cloud Build

**Comment by alvarowolfx** [comment]
The project here has the `.pio` folder in `.gitignore`. Uploading the `.pio` from the source seems weird, as the whole point is to build the binary from scratch on the CI env. Let me know if you have other problems and I can try to help, but seems like you got it to work.

**Comment by ben700** [comment]
Yes I agree,

I'll play with removing the .pio folder, it's the external libraries it's
accessing in there.

I'm building a water quality monitor, recording/monitoring pH, EC, ORP and
Temp. Would like to use AI to clean data in realtime, plus integration into
Google Smart Home especially for setup of device as new product by
customer.

Been looking for a nice solution to recycle keys, maybe Cloud function with
KMS updating IOT once signed with CA

All easy stuff for you!!!  How much money do I owe you now? I'll buy you
something for helping on this even if you don't want any work. But I'm
happy to work a little work package for say 10 days. See how we work
together?

Ben
